version: "3"
services:
  web:
    build:
      context: ../../
      dockerfile: contribute/docker/Dockerfile
    working_dir: /opt/service
    network_mode: host
    env_file:
      - ./.env
    restart: always
    ports:
      - 127.0.0.1:8001:8001
    # setup through .env file
    # environment:
    #   - TGBOT_API_TOKEN
    #   - TGBOT_MODEL_PATH
